openapi: 3.0.3
info:
  title: OPEN API
  description: this is paths
  version: 1.1.0
  

servers:
  - url: http://38.242.155.165:4000
paths:
  #Auth for Desktop
  /api/v1/d/auth/signup:
    $ref: './swagger/desktop/auth.yaml#/paths/SignUp'
  /api/v1/d/auth/login:
    $ref: './swagger/desktop/auth.yaml#/paths/LogIn'

  #Address
  /api/v1/country:
    $ref: './swagger/common/address.yaml#/paths/country'

  /api/v1/country/search:
    $ref: './swagger/common/address.yaml#/paths/countrySearch'

  /api/v1/state:
    $ref: './swagger/common/address.yaml#/paths/state'

  /api/v1/city:
    $ref: './swagger/common/address.yaml#/paths/city'

  /api/v1/city/search:
    $ref: './swagger/common/address.yaml#/paths/citySearch'

  /api/v1/city/bystate:
    $ref: './swagger/common/address.yaml#/paths/cityByState'

  #Allergy
  /api/v1/allergy:
    $ref: './swagger/common/allergy.yaml#/paths/allergy'

  /api/v1/allergy/{id}:
    $ref: './swagger/common/allergy.yaml#/paths/allergyId'

  /api/v1/allergy/search:
    $ref: './swagger/common/allergy.yaml#/paths/allergySearch'

  #Contact
  /api/v1/contact:
    $ref: './swagger/common/contact.yaml#/paths/contact'

  /api/v1/contact/{id}:
    $ref: './swagger/common/contact.yaml#/paths/contactId'

  /api/v1/contact/search:
    $ref: './swagger/common/contact.yaml#/paths/contactSearch'


  #Contact Category
  /api/v1/contactcategory:
    $ref: './swagger/common/contactcategory.yaml#/paths/contactCategory'

  /api/v1/contactcategory/{id}:
    $ref: './swagger/common/contactcategory.yaml#/paths/contactCategoryId'


  #Disease
  /api/v1/disease:
    $ref: './swagger/common/disease.yaml#/paths/disease'

  /api/v1/disease/{id}:
    $ref: './swagger/common/disease.yaml#/paths/diseaseId'

  /api/v1/disease/search:
    $ref: './swagger/common/disease.yaml#/paths/diseaseSearch'


  #Drug
  /api/v1/drug:
    $ref: './swagger/common/drug.yaml#/paths/drug'

  /api/v1/drug/{id}:
    $ref: './swagger/common/drug.yaml#/paths/drugId'

  /api/v1/drug/search:
    $ref: './swagger/common/drug.yaml#/paths/drugSearch'

  #Habit
  /api/v1/habit:
    $ref: './swagger/common/habit.yaml#/paths/habit'

  /api/v1/habit/{id}:
    $ref: './swagger/common/habit.yaml#/paths/habitId'

  /api/v1/habit/search:
    $ref: './swagger/common/habit.yaml#/paths/habitSearch'

  #Measure
  /api/v1/measure:
    $ref: './swagger/common/measure.yaml#/paths/measure'

  /api/v1/measure/{id}:
    $ref: './swagger/common/measure.yaml#/paths/measureId'

  /api/v1/measure/search:
    $ref: './swagger/common/measure.yaml#/paths/measureSearch'

  #Reason
  /api/v1/reason:
    $ref: './swagger/common/reason.yaml#/paths/reason'

  /api/v1/reason/{id}:
    $ref: './swagger/common/reason.yaml#/paths/reasonId'

  /api/v1/reason/search:
    $ref: './swagger/common/reason.yaml#/paths/reasonSearch'

  #Speciality
  /api/v1/speciality:
    $ref: './swagger/common/speciality.yaml#/paths/speciality'

  /api/v1/speciality/{id}:
    $ref: './swagger/common/speciality.yaml#/paths/specialityId'

  /api/v1/speciality/search:
    $ref: './swagger/common/speciality.yaml#/paths/specialitySearch'

  #Symptom
  /api/v1/symptom:
    $ref: './swagger/common/symptom.yaml#/paths/symptom'

  /api/v1/symptom/{id}:
    $ref: './swagger/common/symptom.yaml#/paths/symptomId'

  /api/v1/symptom/search:
    $ref: './swagger/common/symptom.yaml#/paths/symptomSearch'



components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, arbitrary value for documentation purpos

  schemas:
    Doctor:
      $ref: './swagger/components/schemas/doctor.yaml#/components/schemas/doctor'
    Patient:
      $ref: './swagger/components/schemas/patient.yaml#/components/schemas/patient'
    Contact:
      $ref: './swagger/components/schemas/contact.yaml#/components/schemas/contact'
    ContactCategory:
      $ref: './swagger/components/schemas/contactCategory.yaml#/components/schemas/contactCategory'
    Appointment:
      $ref: './swagger/components/schemas/appointment.yaml#/components/schemas/appointment'
    Address:
      $ref: './swagger/components/schemas/address.yaml#/components/schemas/address'
    Country:
      $ref: './swagger/components/schemas/country.yaml#/components/schemas/country'
    State:
      $ref: './swagger/components/schemas/state.yaml#/components/schemas/state'
    City:
      $ref: './swagger/components/schemas/city.yaml#/components/schemas/city'
    Metadata:
      $ref: './swagger/components/schemas/metadata.yaml#/components/schemas/metadata'
    Allergy:
      $ref: './swagger/components/schemas/allergy.yaml#/components/schemas/allergy'
    patientAllergy:
      $ref: './swagger/components/schemas/patientAllergy.yaml#/components/schemas/patientAllergy'
    Reason:
      $ref: './swagger/components/schemas/reason.yaml#/components/schemas/reason'
    User:
      $ref: './swagger/components/schemas/user.yaml#/components/schemas/user'
    patientDisease:
      $ref: './swagger/components/schemas/patientDisease.yaml#/components/schemas/patientDisease'
    patientHabit:
      $ref: './swagger/components/schemas/patientHabit.yaml#/components/schemas/PatientHabit'
    patientMeasure:
      $ref: './swagger/components/schemas/patientMeasure.yaml#/components/schemas/PatientMeasure'
    patientSymptom:
      $ref: './swagger/components/schemas/patientSymptom.yaml#/components/schemas/PatientSymptom'
    BilanLine:
      $ref: './swagger/components/schemas/bilanLine.yaml#/components/schemas/BilanLine'
    BioAnalyse:
      $ref: './swagger/components/schemas/bioAnalyse.yaml#/components/schemas/BioAnalyse'
    BioAnalyseCategory:
      $ref: './swagger/components/schemas/bioAnalyseCategory.yaml#/components/schemas/BioAnalyseCategory'
    Drug:
      $ref: './swagger/components/schemas/drug.yaml#/components/schemas/Drug'
    Establishment:
      $ref: './swagger/components/schemas/establishment.yaml#/components/schemas/Establishment'
    MedicalAct:
      $ref: './swagger/components/schemas/medicalAct.yaml#/components/schemas/MedicalAct'
    PatientAntecedent:
      $ref: './swagger/components/schemas/patientAntecedent.yaml#/components/schemas/PatientAntecedent'
    PatientBilan:
      $ref: './swagger/components/schemas/patientBilan.yaml#/components/schemas/PatientBilan'
    PatientBloodDonation:
      $ref: './swagger/components/schemas/patientBloodDonation.yaml#/components/schemas/PatientBloodDonation'
    PatientConsultation:
      $ref: './swagger/components/schemas/patientConsultation.yaml#/components/schemas/PatientConsultation'
    PatientDocument:
      $ref: './swagger/components/schemas/patientDocument.yaml#/components/schemas/PatientDocument'
    PatientPrescription:
      $ref: './swagger/components/schemas/patientPrescription.yaml#/components/schemas/PatientPrescription'
    PatientTreatment:
      $ref: './swagger/components/schemas/patientTreatment.yaml#/components/schemas/PatientTreatment'
    PatientVaccine:
      $ref: './swagger/components/schemas/patientVaccine.yaml#/components/schemas/PatientVaccine'
    PrescriptionLines:
      $ref: './swagger/components/schemas/prescriptionLines.yaml#/components/schemas/PrescriptionLines'
    Vaccine:
      $ref: './swagger/components/schemas/vaccine.yaml#/components/schemas/Vaccine'
    task:
      $ref: './swagger/components/schemas/task.yaml#/components/schemas/Task'
    taskList:
      $ref: './swagger/components/schemas/taskList.yaml#/components/schemas/TaskList'

    Disease:
      $ref: './swagger/components/schemas/disease.yaml#/components/schemas/disease'
    Habit:
      $ref: './swagger/components/schemas/habit.yaml#/components/schemas/Habit'
    Measure:
      $ref: './swagger/components/schemas/measure.yaml#/components/schemas/Measure'
    Symptom:
      $ref: './swagger/components/schemas/symptom.yaml#/components/schemas/Symptom'
