openapi: 3.0.3
info:
  title: OPEN API
  description: this is paths
  version: 1.1.0
paths:
  #Address
  /api/v1/country:
    $ref: './swagger/common/address.yaml#/paths/~1country'

  /api/v1/country/search:
    $ref: './swagger/common/address.yaml#/paths/~1countrySearch'

  /api/v1/state:
    $ref: './swagger/common/address.yaml#/paths/~1state'

  /api/v1/city:
    $ref: './swagger/common/address.yaml#/paths/~1city'

  /api/v1/city/search:
    $ref: './swagger/common/address.yaml#/paths/~1citySearch'

  /api/v1/city/bystate:
    $ref: './swagger/common/address.yaml#/paths/~1cityByState'

  #Allergy
  /api/v1/allergy:
    $ref: './swagger/common/allergy.yaml#/paths/~1allergy'

  /api/v1/allergy/{id}:
    $ref: './swagger/common/allergy.yaml#/paths/~1allergyId'

  /api/v1/allergy/search:
    $ref: './swagger/common/allergy.yaml#/paths/~1allergySearch'

  #Contact
  /api/v1/contact:
    $ref: './swagger/common/contact.yaml#/paths/~1contact'

  /api/v1/contact/{id}:
    $ref: './swagger/common/contact.yaml#/paths/~1contactId'

  /api/v1/contact/search:
    $ref: './swagger/common/contact.yaml#/paths/~1contactSearch'


  #Contact Category
  /api/v1/contactcategory:
    $ref: './swagger/common/contactcategory.yaml#/paths/~1contactCategory'

  /api/v1/contactcategory/{id}:
    $ref: './swagger/common/contactcategory.yaml#/paths/~1contactCategoryId'


  #Disease
  /api/v1/disease:
    $ref: './swagger/common/disease.yaml#/paths/~1disease'

  /api/v1/disease/{id}:
    $ref: './swagger/common/disease.yaml#/paths/~1diseaseId'

  /api/v1/disease/search:
    $ref: './swagger/common/disease.yaml#/paths/~1diseaseSearch'


  #Drug
  /api/v1/drug:
    $ref: './swagger/common/drug.yaml#/paths/~1drug'

  /api/v1/drug/{id}:
    $ref: './swagger/common/drug.yaml#/paths/~1drugId'

  /api/v1/drug/search:
    $ref: './swagger/common/drug.yaml#/paths/~1drugSearch'

  #Habit
  /api/v1/habit:
    $ref: './swagger/common/habit.yaml#/paths/~1habit'

  /api/v1/habit/{id}:
    $ref: './swagger/common/habit.yaml#/paths/~1habitId'

  /api/v1/habit/search:
    $ref: './swagger/common/habit.yaml#/paths/~1habitSearch'

  #Measure
  /api/v1/measure:
    $ref: './swagger/common/measure.yaml#/paths/~1measure'

  /api/v1/measure/{id}:
    $ref: './swagger/common/measure.yaml#/paths/~1measureId'

  /api/v1/measure/search:
    $ref: './swagger/common/measure.yaml#/paths/~1measureSearch'

  #Reason
  /api/v1/reason:
    $ref: './swagger/common/reason.yaml#/paths/~1reason'

  /api/v1/reason/{id}:
    $ref: './swagger/common/reason.yaml#/paths/~1reasonId'

  /api/v1/reason/search:
    $ref: './swagger/common/reason.yaml#/paths/~1reasonSearch'

  #Speciality
  /api/v1/speciality:
    $ref: './swagger/common/speciality.yaml#/paths/~1speciality'

  /api/v1/speciality/{id}:
    $ref: './swagger/common/speciality.yaml#/paths/~1specialityId'

  /api/v1/speciality/search:
    $ref: './swagger/common/speciality.yaml#/paths/~1specialitySearch'

  #Symptom
  /api/v1/symptom:
    $ref: './swagger/common/symptom.yaml#/paths/~1symptom'

  /api/v1/symptom/{id}:
    $ref: './swagger/common/symptom.yaml#/paths/~1symptomId'

  /api/v1/symptom/search:
    $ref: './swagger/common/symptom.yaml#/paths/~1symptomSearch'



components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, arbitrary value for documentation purpos

  schemas:
    Doctor:
      $ref: './swagger/components/schemas/doctor.yaml#/components/schemas/doctor'
    Patient:
      $ref: './swagger/components/schemas/patient.yaml#/components/schemas/patient'
    Contact:
      $ref: './swagger/components/schemas/contact.yaml#/components/schemas/contact'
    ContactCategory:
      $ref: './swagger/components/schemas/contactCategory.yaml#/components/schemas/contactCategory'
    Appointment:
      $ref: './swagger/components/schemas/appointment.yaml#/components/schemas/appointment'
    Address:
      $ref: './swagger/components/schemas/address.yaml#/components/schemas/address'
    Country:
      $ref: './swagger/components/schemas/country.yaml#/components/schemas/country'
    State:
      $ref: './swagger/components/schemas/state.yaml#/components/schemas/state'
    City:
      $ref: './swagger/components/schemas/city.yaml#/components/schemas/city'
    Metadata:
      $ref: './swagger/components/schemas/metadata.yaml#/components/schemas/metadata'
    Allergy:
      $ref: './swagger/components/schemas/allergy.yaml#/components/schemas/allergy'
    patientAllergy:
      $ref: './swagger/components/schemas/patientAllergy.yaml#/components/schemas/patientAllergy'
    Reason:
      $ref: './swagger/components/schemas/reason.yaml#/components/schemas/reason'
    User:
      $ref: './swagger/components/schemas/user.yaml#/components/schemas/user'
    Disease:
      $ref: './swagger/components/schemas/disease.yaml#/components/schemas/disease'
    patientDisease:
      $ref: './swagger/components/schemas/patientDisease.yaml#/components/schemas/patientDisease'
    patientHabit:
      $ref: './swagger/components/schemas/patientHabit.yaml#/components/schemas/PatientHabit'
    Habit:
      $ref: './swagger/components/schemas/habit.yaml#/components/schemas/Habit'