openapi: 3.0.3
info:
  title: OPEN API
  description: this is paths
  version: 1.1.0
paths:
  #Auth
  /api/v1/auth/signup:
    $ref: './swagger/mobile/auth.yaml#/paths/~1SignUp'
  /api/v1/auth/login:
    $ref: './swagger/mobile/auth.yaml#/paths/~1LogIn'

  #Doctor
  /api/v1/m/doctor:
    $ref: './swagger/mobile/doctor.yaml#/paths/~1Doctor'
  /api/v1/m/doctor/search:
    $ref: './swagger/mobile/doctor.yaml#/paths/~1doctorSearch'

  #patient Allergy
  /api/v1/m/patient/allergy:
    $ref: './swagger/mobile/patientAllergy.yaml#/paths/~1patientAllergy'
  /api/v1/m/patient/allergy/{id}:
    $ref: './swagger/mobile/patientAllergy.yaml#/paths/~1patientAllergyId'

  #patient Disease
  /api/v1/m/patient/disease:
    $ref: './swagger/mobile/patientDisease.yaml#/paths/~1patientDisease'
  /api/v1/m/patient/disease/{id}:
    $ref: './swagger/mobile/patientDisease.yaml#/paths/~1patientDiseaseId'

  #patient Habit
  /api/v1/m/patient/habit:
    $ref: './swagger/mobile/patientHabit.yaml#/paths/~1patientHabit'
  /api/v1/m/patient/habit/{id}:
    $ref: './swagger/mobile/patientHabit.yaml#/paths/~1patientHabitId'

  #patient Measure
  /api/v1/m/patient/measure:
    $ref: './swagger/mobile/patientMeasure.yaml#/paths/~1patientMeasure'
  /api/v1/m/patient/measure/{id}:
    $ref: './swagger/mobile/patientMeasure.yaml#/paths/~1patientMeasureId'

  # Appointment
  /api/v1/m/appointment:
    $ref: './swagger/mobile/appointment.yaml#/paths/~1appointment'

  /api/v1/m/appointment/{id}:
    $ref: './swagger/mobile/appointment.yaml#/paths/~1appointmentId'

  /api/v1/m/appointment/search:
    $ref: './swagger/mobile/appointment.yaml#/paths/~1appointmentSearch'


components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, arbitrary value for documentation purpos

  schemas:
    Doctor:
      $ref: './swagger/components/schemas/doctor.yaml#/components/schemas/doctor'
    Patient:
      $ref: './swagger/components/schemas/patient.yaml#/components/schemas/patient'
    Contact:
      $ref: './swagger/components/schemas/contact.yaml#/components/schemas/contact'
    ContactCategory:
      $ref: './swagger/components/schemas/contactCategory.yaml#/components/schemas/contactCategory'
    Appointment:
      $ref: './swagger/components/schemas/appointment.yaml#/components/schemas/appointment'
    Address:
      $ref: './swagger/components/schemas/address.yaml#/components/schemas/address'
    Country:
      $ref: './swagger/components/schemas/country.yaml#/components/schemas/country'
    State:
      $ref: './swagger/components/schemas/state.yaml#/components/schemas/state'
    City:
      $ref: './swagger/components/schemas/city.yaml#/components/schemas/city'
    Metadata:
      $ref: './swagger/components/schemas/metadata.yaml#/components/schemas/metadata'
    Allergy:
      $ref: './swagger/components/schemas/allergy.yaml#/components/schemas/allergy'
    patientAllergy:
      $ref: './swagger/components/schemas/patientAllergy.yaml#/components/schemas/patientAllergy'
    Reason:
      $ref: './swagger/components/schemas/reason.yaml#/components/schemas/reason'
    User:
      $ref: './swagger/components/schemas/user.yaml#/components/schemas/user'
    patientDisease:
      $ref: './swagger/components/schemas/patientDisease.yaml#/components/schemas/patientDisease'
    patientHabit:
      $ref: './swagger/components/schemas/patientHabit.yaml#/components/schemas/PatientHabit'
    patientMeasure:
      $ref: './swagger/components/schemas/patientMeasure.yaml#/components/schemas/PatientMeasure'

    Disease:
      $ref: './swagger/components/schemas/disease.yaml#/components/schemas/disease'
    Habit:
      $ref: './swagger/components/schemas/habit.yaml#/components/schemas/Habit'
    Measure:
      $ref: './swagger/components/schemas/measure.yaml#/components/schemas/Measure'

