openapi: 3.0.3
info:
  title: OPEN API
  description: this is paths
  version: 1.1.0

paths:

  /api/v1/disease:
    # [GET] GET ALL
    get:
      tags:
        - Disease
      summary: Fetch diseases
      description: Fetch diseases
      parameters:
        - name: page
          in: query
          description: Pagination page
          example : 1
          schema:
            type: integer
        - name: limit
          in: query
          description: number of elements per page
          example: 20
          schema:
            type: integer
      security:
        - bearerAuth: [Authorization]
      responses:
        '200':
          description: "OK"
        '500':
          description: "Server Error"

  /api/v1/disease/{id}:
    # [GET] GET ONE
    get:
      tags:
        - Disease
      summary: Fetch one disease
      description: Fetch one disease
      parameters:
        - name: id
          in: path
          description: disease Id
          required: true
          example: id_Disease
          schema:
            type: string
      security:
        - bearerAuth: [Authorization]
      responses:
        '200':
          description: "OK"
        '500':
          description: "Server Error"
        '400':
          description: "Bad Request"
        '409':
          description: "Conflict"

  /api/v1/disease/search:
    # [GET] SEARCH
    get:
      tags:
        - Disease
      summary: search for disease
      description: search for disease
      parameters:
        - name: q
          in: query
          description: search query
          required: true
          example: Query
          schema:
            type: string

        - name: page
          in: query
          description: Pagination page
          example: 1
          schema:
            type: string

        - name: limit
          in: query
          description: number of elements per page
          example: 20
          schema:
            type: integer


      security:
        - bearerAuth: [Authorization]
      responses:
        '200':
          description: "OK"
        '500':
          description: "Server Error"

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, arbitrary value for documentation purpos
